#
#country:
#  countryConfig:
#    HZSZF:
#      - url: https://172.18.111.113:7054
#        path: src/crypto-config/peerOrganizations/HZSZF.citybrain.com/ca/ca.HZSZF.citybrain.com-cert.pem
country:
  countryConfig:
    aue:
      - lang: zh
        isDefault: true
    hk:
      - lang: zh
        isDefault: true

orgs:
  - id: HZSZF
    Name: 杭州市政府
    useTls: true
    ca:
      domain: ca.HZSZF.citybrain.com
      protocol: http
      pemFile:
    peers:
      - domain: peer0.HZSZF.citybrain.com
        protocol: grpc # grpc or grpcs
        pemFile:
      - domain: peer1.HZSZF.citybrain.com
        protocol: grpc
        pemFile:
    channels:
      - citybrainchannel
server:
  port: 1008

com:
  yunyang:
    caClient:
      url: https://172.18.111.113:7054
      caPemPath: src/crypto-config/peerOrganizations/HZSZF.citybrain.com/ca/ca.HZSZF.citybrain.com-cert.pem
    orgs:
      - id: HZSZF
        Name: 杭州市政府
        useTls: true
        ca:
          domain: ca.HZSZF.citybrain.com
          protocol: http
          pemFile:
        peers:
          - domain: peer0.HZSZF.citybrain.com
            protocol: grpc # grpc or grpcs
            pemFile:
          - domain: peer1.HZSZF.citybrain.com
            protocol: grpc
            pemFile:
        channels:
          - citybrainchannel
#    tes:
#      maps:
#        key1: 15
#        key2: 2
