#
#country:
#  countryConfig:
#    HZSZF:
#      - url: https://172.18.111.113:7054
#        path: src/crypto-config/peerOrganizations/HZSZF.citybrain.com/ca/ca.HZSZF.citybrain.com-cert.pem
country:
  countryConfig:
    aue:
      - lang: zh
        isDefault: true
    hk:
      - lang: zh
        isDefault: true

orgs:
  - id: HZSZF
    Name: 杭州市政府
    useTls: true
    ca:
      domain: ca.HZSZF.citybrain.com
      protocol: http
      pemFile:
    peers:
      - domain: peer0.HZSZF.citybrain.com
        protocol: grpc # grpc or grpcs
        pemFile:
      - domain: peer1.HZSZF.citybrain.com
        protocol: grpc
        pemFile:
    channels:
      - citybrainchannel
server:
  port: 1008

com:
  yunyang:
    caClient:
#      url: https://172.18.111.166:7054
#      caPemPath: src/testCrypto/crypto/hzssjzyj.citybrain-test.com/ca/ca.hzssjzyj.citybrain-test.com-cert.pem
#       url: https://172.18.71.135:8054
#       caPemPath: src/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
       url: https://172.18.71.135:7054
       caPemPath: src/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
#      url: http://192.168.137.7:7054
#      caPemPath: src/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
    orgs:
      - id: HZSZF
        Name: 杭州市政府
        useTls: true
        ca:
          domain: ca.HZSZF.citybrain.com
          protocol: http
          pemFile:
        peers:
          - domain: peer0.HZSZF.citybrain.com
            protocol: grpc # grpc or grpcs
            pemFile:
          - domain: peer1.HZSZF.citybrain.com
            protocol: grpc
            pemFile:
        channels:
          - citybrainchannel
